# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
#  config.vm.define "vb32" do |vb32|
#    vb32.vm.box = "ubuntu/trusty32"
#    vb32.vm.provider :virtualbox do |vb|
#      vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
#      vb.name = "cns2017.32bit"
#    end
#  end

  config.vm.define "vb64" do |vb64|
    vb64.vm.box = "ubuntu/trusty64"
    vb64.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.name = "cns2017"
    end
  end
  
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.gui = true
  end
 

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      # ansible.verbose = "v"
  end
end
  
