# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = "hbpschool2016"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
   
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.name = VM_NAME
    vb.gui = true
  end
 
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      # ansible.verbose = "v"
  end
end
  
